/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/resting_zone_museum.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.673, 0]} scale={2.778}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Gear003.geometry}
          material={materials['Marble.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Gear003_1.geometry}
          material={materials['Desk 1']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.dobj003.geometry}
        material={materials['Back Shelf']}
        position={[0, 2.229, 0]}
        scale={2.778}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.dobj002.geometry}
        material={materials['Desk 1']}
        position={[0, 2.255, 0]}
        scale={2.778}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.dobj001.geometry}
        material={materials['Gold Sheen']}
        position={[0, 1.948, 0]}
        scale={2.778}
      />
      <group position={[0, 2.229, 0]} scale={2.778}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dmesh006.geometry}
          material={materials.Material_glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dmesh006_1.geometry}
          material={materials['Back Shelf']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Gear001.geometry}
        material={materials.fabric_leather_02}
        position={[0, 0.899, 0]}
        scale={2.656}
      />
    </group>
  )
}

useGLTF.preload('/resting_zone_museum.glb')